site_name: "Mork Developers Guide"
theme:
    name: "readthedocs"
    features:
        - content.code.select
        - content.code.annotate
plugins:
    - search
    - mermaid2
    - awesome-pages

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - md_in_html
    - pymdownx.arithmatex:
        generic: true

extra_javascript:
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

